Wok 592 validate iip
kb-dk/ds-image pull request #15
Opened 2023-02-23 08:48 UTC by VictorHarbo

Implements validation of IIP parameters.

2023-02-23 10:01 UTC, tokee requested changes
One (1) coding error. The rest is only suggestions for adjustments.

2023-02-23 10:01 UTC, tokee commented on src/test/java/dk/kb/image/IIPValidationTest.java
> +public class IIPValidationTest {
Overall very thorough checking for problematic values, but you are missing checks for _valid_ values as well as missing (`null`) values.

2023-02-23 10:23 UTC, VictorHarbo commented on src/main/java/dk/kb/image/IIPParamValidation.java
> +        if (cvt != null) {
The null check in line 107 was meant to ensure, that the service doesn't fail, when CVT is not in use. For example when asking for JTL or PTL

2023-02-23 12:08 UTC, VictorHarbo commented on src/main/java/dk/kb/image/IIPParamValidation.java
> +        if (cvt == null || cvt.isEmpty() && wid != null) {
`wid` is of type long. I can make this check by doing `!wid.toString().isEmpty()` but I don't know if that would make any sense as I cant see how `wid` can be an empty string in the first place?

2023-02-23 12:08 UTC, VictorHarbo commented on src/main/java/dk/kb/image/IIPParamValidation.java
> +        if (cvt == null || cvt.isEmpty() && hei != null) {
`hei` is of type long. I can make this check by doing `!hei.toString().isEmpty()` but I don't know if that would make any sense as I cant see how `hei` can be an empty string in the first place?

2023-02-27 08:40 UTC, VictorHarbo commented on src/test/java/dk/kb/image/IIPValidationTest.java
> +        String actualHMessage = exceptionH.getMessage();
We didn't really find the perfect solution for this over lunch last week. I will try to implement a check on a higher level.

2023-02-28 09:48 UTC, tokee commented on src/main/java/dk/kb/image/IIPParamValidation.java
> +        if (jtl.size() != 0 & jtl != null & !jtl.isEmpty()) {
The problem still exists at line 217, where `if ((cvt == null || cvt.isEmpty()) && (!rgn.isEmpty() || rgn != null)) {` will fail with a ǸullPointerException` if `rgn` is `null`.

2023-02-28 09:51 UTC, tokee commented on src/main/java/dk/kb/image/IIPParamValidation.java
> +            int pairTwoComma = pairTwo.indexOf(",");
Very nice now.

2023-02-28 09:56 UTC, tokee commented on src/test/java/dk/kb/image/IIPValidationTest.java
> +        String actualHMessage = exceptionH.getMessage();
Let's leave them as-is. Changing them now is the same work as changing them later and if the Exceptions are never adjusted there is no need for changing.

2023-03-02 12:17 UTC, merged